### PR TITLE
Move unread functionality to label configuration.

### PR DESCRIPTION
**Pull request by jewzaam**
This allows having labels that will delete unread emails and also NOT delete unread emails.

### CODE REVIEW

**Comment by scrith** [comment]
I'm going to let this one soak in my head for a while since it does double the number of needed labels.

**Comment by jewzaam** [comment]
Maybe add a 3rd tier of labels:

- read
- unread
- all

And then they don't need to be managed in code.

**Comment by scrith** [comment]
I've reworked the script to add this functionality using a label.  Rather than multiplying each retention policy label to include _read, _unread, etc.  A standalone label retention/keepunread is used.  This label can be applied to any message to override cleanup handling.  This was done in conjunction with an expansion of the script to also add rules for auto-archiving emails as well.  This feature is now present in the codebase, so I will close this pull request.

**Comment by scrith** [comment]
Also, and sorry about this, but I also renamed the project and main script to more accurately reflect what this project is all about.  You'll probably need to do a new clone to get the update.

**Comment by jewzaam** [comment]
Thanks for the update, glad to see this rolled in.  I've got this stuff integrated into some other mail management scripts but will merge it into that sometime in the next week.  Cheers!

**Pull request closed without merging**
